#!/usr/bin/python
#
# Copyright (C) 2007 Red Hat, Inc.
#
# Author: Phil Knirsch
#
# Process the multiple logfiles of pyrpmcheckinstall and automatically
# splits up the logfiles in per package logfiles and generates a nice overview
# html page from it.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Library General Public License as published by
# the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# Copyright 2004, 2005 Red Hat, Inc.
#
#

import sys, time

if len(sys.argv) < 3:
    print "Usage: "+sys.argv[0]+" LOGFILE [LOGFILE..] RESULTDIR"
    sys.exit(1)

resultdir = sys.argv[-1]
logfiles = sys.argv[1:-1]
resultfile = open(resultdir+"/index.html", "w")
print >>resultfile,"""
<html>
<body>
<H3>
Results for """+logfiles[0]+"""<br>
Date: """+time.ctime()+"""</H3>
<table border=1>
<tr><th>Package</th><th>Status</th><th>Logfile</th></tr>
"""

pkgnames = []
for lfile in logfiles:
    lines = open(lfile).readlines()
    RES = None
    founderr = False
    for l in lines:
        if l.startswith("Updating package "):
            if RES != None:
                if founderr:
                    print >>resultfile, "<td bgcolor=\"red\">Failed</td>"
                else:
                    print >>resultfile, "<td bgcolor=\"lime\">Success</td>"
                pkgname = pkgname.replace(":", "%3A")
                print >>resultfile, "<td><a href=\""+pkgname+"\">Log</a></td></tr>"
                RES.close()
            pkgname = l[l.index(":")+2:-1]
            pkgnames.append(pkgname)
            RES = open(resultdir+"/"+pkgname, "w")
            founderr = False
            print >>resultfile, "<tr><td>"+pkgname+"</td>"
        else:
            if RES != None:
                if l.find("ERROR") >= 0:
                    founderr = True
                print >>RES, l[:-1]

    if RES != None:
        if founderr:
            print >>resultfile, "<td bgcolor=\"red\">Failed</td>"
        else:
            print >>resultfile, "<td bgcolor=\"lime\">Success</td>"
        pkgname = pkgname.replace(":", "%3A")
        print >>resultfile, "<td><a href=\""+pkgname+"\">Log</a></td></tr>"
        RES.close()

print >>resultfile,"""
</table>
</body>
</html>
"""

resultfile.close()

# vim:ts=4:sw=4:showmatch:expandtab
