#!/usr/bin/python

import sys, os
from pyrpmlib import *

for i in sys.argv[1:]:
    rpmio = getRpmIOFactory("file:/"+i)
    (key, value) = rpmio.read()
    while key != "EOF" and key != "None" :
        print key
        (key, value) = rpmio.read()
# vim:ts=4:sw=4:showmatch:expandtab
