#!/usr/bin/python

import sys, os
from pyrpmlib import *

for i in sys.argv[1:]:
    rpm = RpmPackage("file:/"+i)
    rpm.read(tags="version", ntags="name")
#    if type(rpm["epoch"]) != type(None) and type(rpm["epoch"]) != type(()):
#        print type(rpm["epoch"])
    print rpm.getNEVRA()
# vim:ts=4:sw=4:showmatch:expandtab
