#!/usr/bin/python

import sys, time
from pyrpm import *

rpms = []
for i in sys.argv[1:]:
    pkg = RpmPackage(i)
#    rpm.read(tags=("name", "epoch", "version", "release", "arch", "providename", "provideflags", "provideversion", "requirename", "requireflags", "requireversion", "obsoletename", "obsoleteflags", "obsoleteversion", "conflictname", "conflictflags", "conflictversion", "filesizes", "filemodes", "filerdevs", "filemtimes", "filemd5s", "filelinktos", "fileflags", "fileusername", "filegroupname", "fileverifyflags", "filedevices", "fileinodes", "filelangs", "dirindexes", "basenames", "dirnames"))
    pkg.read()
    (fname, fdata) = pkg.io.read()
    while fname != "EOF":
	(fname, fdata) = pkg.io.read()
    pkg.close()
    rpms.append(pkg)
#time.sleep(30)
