#!/usr/bin/python

import sys, os
from pyrpmlib import *
from rpmconstants import *

for i in sys.argv[1:]:
    rpm = RpmPackage("file:/"+i)
    rpm.open()
    pid = os.fork()
    if pid != 0:
        os.wait()
        rpm.close()
        continue
    else:
        os.chroot("/mnt/build/pyrpm-fc3-i386/")
        rpm.install()
	sys.exit()
# vim:ts=4:sw=4:showmatch:expandtab
