#!/usr/bin/python
import unittest

class TestFunctions(unittest.TestCase):
    def __init__(self, args):
        unittest.TestCase.__init__(self, args)

    def tearDown(self):
        pass
        
    def testNormalizeList(self):
        """Testing functions.normalizeList()"""
        list = [ "a", "a", "b", "c", "c" ]
        functions.normalizeList(list)
        self.assertEqual(list, ['a', 'b', 'c'])
        list = [ "a", "a"]
        functions.normalizeList(list)
        self.assertEqual(list, ['a'])
        list = [ "a", "b"]
        functions.normalizeList(list)
        self.assertEqual(list, ['a', 'b'])


def suite():
    suite = unittest.TestSuite()
    suite = unittest.makeSuite(TestFunctions,'test')
    return suite

if __name__ == "__main__":
    import sys
    do_coverage = 1
    if do_coverage:
        import coverage
        coverage.erase()
        coverage.start()
        
    import functions 
    testRunner = unittest.TextTestRunner(verbosity=2)
    result = testRunner.run(suite())
    
    if do_coverage:
        coverage.stop()    
        m = sys.modules.values()
        coverage.the_coverage.report(functions, show_missing=1 )
        
    sys.exit(not result.wasSuccessful())
    
__author__ = "Harald Hoyer <harald@redhat.com>"
__date__ = "$Date$"
__version__ = "$Revision$"
