#!/usr/bin/python

import sys, os
from pyrpm import *

for i in sys.argv[1:]:
    rpmio = getRpmIOFactory(rpmconfig, "file:/"+i)
    try:
        key = rpmio.read()[0]
        while key != "EOF":
            print key
            key = rpmio.read()[0]
    except (ValueError, IOError), e:
        sys.stderr.write("Error reading %s: %s\n" % (i, e))
# vim:ts=4:sw=4:showmatch:expandtab
