#!/usr/bin/python

import sys
from pyrpm import *

rpms = []
for i in sys.argv[1:]:
    rpm = RpmPackage(rpmconfig, "file://"+i)
    try:
        rpm.read()
    except (IOError, ValueError), e:
        sys.stderr.write("%s: %s\n" % (i, e))
        continue
    if not rpm.has_key("basenames"):
        continue
    flist = []
    for f in rpm["filenames"]:
        flist.append(f)
    rpm["oldfilenames"] = flist
    orig_dirnames = rpm["dirnames"]
    orig_dirindexes = rpm["dirindexes"]
    orig_basenames = rpm["basenames"]
    del rpm["dirnames"], rpm["dirindexes"], rpm["basenames"]
    rpm.generateFileNames()
    for i in xrange(len(rpm["basenames"])):
        if orig_basenames[i] != rpm["basenames"][i]:
            print "Basename difference for pkg %s at index %i: %s != %s" % (rpm.getNEVRA(), i, orig_basenames[i], rpm["basenames"][i])
        if orig_dirindexes[i] != rpm["dirindexes"][i]:
            print "Dirindexes difference for pkg %s at index %i: %s != %s" % (rpm.getNEVRA(), i, orig_dirindexes[i], rpm["dirindexes"][i])
    for i in xrange(len(rpm["dirnames"])):
        if orig_dirnames[i] != rpm["dirnames"][i]:
            print "Dirnames difference for pkg %s at index %i: %s != %s" % (rpm.getNEVRA(), i, orig_dirnames[i], rpm["dirnames"][i])
    for i in xrange(len(rpm["requirename"])):
        if isLegacyPreReq(rpm["requireflags"][i]) or \
           isErasePreReq(rpm["requireflags"][i]):
            if rpm["requirename"][i].startswith("rpmlib("):
                continue
            print rpm.getNEVRA(), rpm["requirename"][i]
#    print "dirnames = ", rpm["dirnames"]
#    print "dirindexes = ", rpm["dirindexes"]
#    print "basenames = ", rpm["basenames"]
#    for f in rpm["filenames"]:
#	rfi = rpm.getRpmFileInfo(f)
#	print rfi.filename, rfi.filecolor
