#!/usr/bin/python

import sys
from pyrpm import *

for i in sys.argv[1:]:
    pkg = RpmPackage(rpmconfig, i)
    try:
        pkg.read()
    except (IOError, ValueError), e:
        sys.stderr.write("%s: %s\n" % (i, e))
        continue
    pkg.source = "file:///var/tmp/"+os.path.basename(i)
    try:
        pkg.close()
        pkg.open("w")
        pkg.write()
    except (OSError, NotImplementedError), e:
        sys.stderr.write("%s: %s\n" % (i, e))
# vim:ts=4:sw=4:showmatch:expandtab
