#!/bin/sh

test -x ./pyrpmyum || exit 1

umask 022

# This can be run as non-root to run resolver/orderer:
#./pyrpminstall -U -r /home/n1 --test n/*.rpm

preparechroot() {
    fuser -k $1 2>/dev/null
    nodev=
    if test x$1 = x--nodev ; then
        nodev=--nodev
        shift
    fi
    umount $1/dev
    umount $1/proc
    mkdir -p $1/{dev,etc/sysconfig,tmp,proc,var/tmp}
    chmod 1777 $1/tmp
    touch $1/etc/fstab
    echo "NETWORKING=yes" > $1/etc/sysconfig/network
    if test x$nodev = x ; then
        mount --bind /dev $1/dev
    else
        mknod -m 0666 $1/dev/null c 1 3
        mknod -m 0666 $1/dev/zero c 1 5
        mknod -m 0644 $1/dev/random c 1 8
        mknod -m 0644 $1/dev/urandom c 1 9
        mknod -m 0660 $1/dev/ttyS0 c 4 64
        mknod -m 0660 $1/dev/ttyS1 c 4 65
        mknod -m 0666 $1/dev/ptmx c 5 2
        mknod -m 0660 $1/dev/md0 b 9 0
        mknod -m 0660 $1/dev/loop0 b 7 1
    fi
    mount -t proc proc $1/proc
}

cleanchroot() {
    test -d $1/dev || return
    test -d $1/proc || return
    umount $1/dev 2> /dev/null
    umount $1/proc 2> /dev/null
    rm -fr $1
}

doinstall() {
    nodev=
    if test x$1 = x--nodev ; then
        nodev=--nodev
        shift
    fi
    test -d $1 || { echo "No dir $1 exists."; return; }
    cleanchroot $2
    preparechroot $nodev $2
    if test x$3 = xrpm ; then
        { time rpm -U --nodigest --nosignature --root=$2 $1/*.rpm; } 2>&1 \
            | tee $2.LOG.install
    else
        #time ./pyrpminstall -U -r $2 $1/*.rpm 2>&1 | tee $2/LOG.install
        # --nofileconflicts
        { time ./pyrpmyum --autoerase -y -r $2 install $1; } 2>&1 \
            | tee $2.LOG.install
    fi
    sync
}

genyumconf() {
cat > /tmp/yum-$2.conf <<EOF
[main]
cachedir=/var/cache/yum
debuglevel=0
errorlevel=0
logfile=/var/log/yum.log
pkgpolicy=newest
assumeyes=1
distroverpkg=fedora-release
gpgcheck=0
tolerant=1
exactarch=0
retries=10
obsoletes=1

[base]
name=Fedora Linux Core $1 - \$basearch
baseurl=file://$FEDORA/$1/\$basearch/os/

[updates]
name=Fedora Linux Core $1 - \$basearch - Updates
baseurl=file://$FEDORA/updates/$1/\$basearch/
EOF
}

DATA=/mnt/data/laroche

if test x$1 = xclean ; then
    for i in $DATA/* ; do
        test -d "$i" || continue
        cleanchroot $2
    done
    exit 0
fi

RELEASED=/mnt/raid/redhat/released
FEDORA=/mnt/raid/fedora
#FEDORA=/mnt/data/laroche/fedora
RPMS=RedHat/RPMS

# Currently non-working:
#doinstall --nodev $RELEASED/RHL-5.2/GOLD/i386/$RPMS $DATA/5.2
#doinstall --nodev $RELEASED/RHL-6.2/GOLD/i386/$RPMS $DATA/6.2
#doinstall --nodev $RELEASED/RHEL-2.1/U6/AS/i386/tree/$RPMS $DATA/2.1-U6-i386

#doinstall --nodev $RELEASED/RHEL-3/U3/AS/i386/tree/$RPMS $DATA/3-U3-i386
#doinstall --nodev $RELEASED/RHEL-3/U4/AS/i386/tree/$RPMS $DATA/3-U4-i386
#doinstall --nodev /mnt/raid/trees/RHEL3U5/i386/$RPMS $DATA/3-U5-i386
#doinstall $RELEASED/RHEL-4/Beta2/AS/i386/tree/$RPMS $DATA/4-Beta2-i386
#doinstall /mnt/raid/trees/RHEL4/i386/$RPMS $DATA/4-trees-i386
#doinstall /mnt/redhat/rel-eng/RHEL4-re1129.0/i386/i386-AS/$RPMS $DATA/4-i386

# Raw FC1 install
doinstall --nodev $FEDORA/1/i386/os/Fedora/RPMS $DATA/FC1-i386
# Update FC1 to updates
{ time ./pyrpmyum -y --autoerase -r $DATA/FC1-i386 update $FEDORA/updates/1/i386 ; } 2>&1 | tee $DATA/FC1-i386.LOG.update
# Update FC1 to testing
{ time ./pyrpmyum -y -vvv --autoerase -r $DATA/FC1-i386 update $FEDORA/updates/testing/1/i386 ; } 2>&1 | tee $DATA/FC1-i386.LOG.update.1
sync

# Raw FC2 install
doinstall --nodev $FEDORA/2/i386/os/Fedora/RPMS $DATA/FC2-i386
# Update FC2 to updates
{ time ./pyrpmyum -y --autoerase -r $DATA/FC2-i386 update $FEDORA/updates/2/i386 ; } 2>&1 | tee $DATA/FC2-i386.LOG.update
# Update FC2 to testing
{ time ./pyrpmyum -y --autoerase -r $DATA/FC2-i386 update $FEDORA/updates/testing/2/i386 ; } 2>&1 | tee $DATA/FC2-i386.LOG.update.1
sync

# Raw FC3 install
doinstall         $FEDORA/3/i386/os/Fedora/RPMS $DATA/FC3-i386
#rm -f $DATA/FC3-i386/var/lib/pyrpm/headers/gnucash*
# Update FC3 to updates
{ time ./pyrpmyum -y --autoerase -r $DATA/FC3-i386 update $FEDORA/updates/3/i386 ; } 2>&1 | tee $DATA/FC3-i386.LOG.update
# Update FC3 to testing
{ time ./pyrpmyum -y --autoerase -r $DATA/FC3-i386 update $FEDORA/updates/testing/3/i386 ; } 2>&1 | tee $DATA/FC3-i386.LOG.update.1
sync

# Install FC1 with all updates
PID=$$
genyumconf(1, $PID)
{ time ./pyrpmyum -y --autoerase -c /tmp/yum-$PID.conf -r $DATA/FC1-2-3-i386 install "*"; } 2>&1 | tee $DATA/FC1-2-3-i386.LOG.update

# Update to FC2 with all updates
genyumconf(2)
{ time ./pyrpmyum -y --autoerase -c /tmp/yum-$PID.conf -r $DATA/FC1-2-3-i386 install "*"; } 2>&1 | tee $DATA/FC1-2-3-i386.LOG.update

# Update to FC3 with all updates
genyumconf(3)
{ time ./pyrpmyum -y --autoerase -c /tmp/yum-$PID.conf -r $DATA/FC1-2-3-i386 install "*"; } 2>&1 | tee $DATA/FC1-2-3-i386.LOG.update
rm -f /tmp/yum-$PID.conf





#doinstall         $FEDORA/3/i386/os/Fedora/RPMS $DATA/FC3-i386-rpm rpm
#rm -f $DATA/FC3-i386-rpm/etc/yum.repos.d/*
#time yum -c $DATA/FC3-i386-rpm/etc/yum.conf --installroot=$DATA/FC3-i386-rpm update 2>&1 | tee $DATA/FC3-i386-rpm.LOG.update


#doinstall         $FEDORA/development/i386/Fedora/RPMS $DATA/FC4-i386

