#!/usr/bin/python

import sys, os
from pyrpm import *

for i in sys.argv[1:]:
    rpm = RpmPackage(rpmconfig, "file:/"+i)
    try:
        rpm.open()
    except IOError, e:
        sys.stderr.write("%s: %s\n" % (i, e))
        continue
    pid = os.fork()
    if pid != 0:
        os.waitpid(pid, 0)
        continue
    else:
        os.chroot("/mnt/build/pyrpm-fc3-i386/")
        try:
            rpm.install()
            rpm.close()
        except (IOError, OSError, ValueError), e:
            sys.stderr.write("%s: %s\n" % (i, e))
	sys.exit()
# vim:ts=4:sw=4:showmatch:expandtab
