#!/usr/bin/python

import sys
from pyrpm import *

rpms = []
for i in sys.argv[1:]:
    rpm = RpmPackage(rpmconfig, "file://"+i, verify=0)
    try:
        rpm.read()
    except (IOError, ValueError), e:
        sys.stderr.write("%s: %s\n" % (i, e))
        continue
    print repr(rpm["install_unknownchecksum"])
    try:
        print repr(rpm["signature"]["gpg"])
    except:
        pass
    print unpack("!2IiI", rpm["signature"]["header_signatures"])
#    print rpm["basenames"]
#    print rpm["dirnames"]
#    print rpm["dirindexes"]
#    for f in rpm["filenames"]:
#	rfi = rpm.getRpmFileInfo(f)
#        print f
#        print rfi.filename, hex(rfi.flags)
    rpms.append(rpm)
