#!/usr/bin/python

import sys
from pyrpm import *

rpms = []
for i in sys.argv[1:]:
    rpm = RpmPackage(rpmconfig, "file://"+i)
    try:
        rpm.read()
    except (IOError, ValueError), e:
        sys.stderr.write("%s: %s\n" % (i, e))
        continue
    for i in xrange(len(rpm["requirename"])):
        print i, rpm["requirename"][i], hex(rpm["requireflags"][i])
    print rpm["signature"]
    #print rpm["requireflags"]
#    print rpm["fileflags"]
#    for f in rpm["filenames"]:
#	rfi = rpm.getRpmFileInfo(f)
#        print rfi.filename, hex(rfi.flags)
    rpms.append(rpm)
