#!/usr/bin/python
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Library General Public License as published by
# the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# Copyright 2004, 2005 Red Hat, Inc.
#
# Author: Phil Knirsch
#

import sys, os.path, getopt

PYRPMDIR = os.path.dirname(__file__) + "/.."
if not PYRPMDIR in sys.path:
    sys.path.append(PYRPMDIR)
from pyrpm import *
from pyrpm import __version__

def usage():
    print """
Convert one rpm database to another
pyrpmdbconvert [-v] sourcedb targetdb

-v:                 Put in verbose mode
sourcedb/targetdb:  URLs to the respective databases.

The URL for a database looks like this:

[pydb:/ | rpmdb:/ | sqlitedb:/]/path/to/databasefiles

Default is rpmdb database format
"""

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "v", [])
    except getopt.error, e:
        print "Error parsing command list arguments: %s" % e
        usage()
        return 0

    for (opt, val) in opts:
        if opt in ["-v", "--verbose"]:
            rpmconfig.verbose += 1

    if len(args) != 2:
        print "Error: You need to specify source and target database"
        usage()
        return 0

    spydb = getRpmDBFactory(rpmconfig, args[0], rpmconfig.buildroot)
    tpydb = getRpmDBFactory(rpmconfig, args[1], rpmconfig.buildroot)

    spydb.read()
    for pkg in spydb.getPkgs():
        tpydb.addPkg(pkg)

    return 1

if __name__ == '__main__':
    if not run_main(main):
        sys.exit(1)

# vim:ts=4:sw=4:showmatch:expandtab
