#!/usr/bin/python
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Library General Public License as published by
# the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# Copyright 2004, 2005 Red Hat, Inc.
#
# Author: Phil Knirsch
#

import sys, os, random

PYRPMDIR = ".."
if not PYRPMDIR in sys.path:
    sys.path.append(PYRPMDIR)
from pyrpm import __version__
from pyrpm import *

def usage():
    print """
INSTALLING, UPGRADING, AND REMOVING PACKAGES using REPOS:
    pyrpmyum install [install-options] PACKAGE_FILE ...
    pyrpmyum groupinstall [install-options] PACKAGE_FILE ...
    pyrpmyum upgrade [install-options] PACKAGE_FILE ...
    pyrpmyum groupupgrade [install-options] PACKAGE_FILE ...
    pyrpmyum update [install-options] PACKAGE_FILE ...
    pyrpmyum groupupdate [install-options] PACKAGE_FILE ...
    pyrpmyum remove [install-options] PACKAGE_FILE ...
    pyrpmyum groupremove [install-options] PACKAGE_FILE ...

general options:
    [-?, --help] [--version]
    [--quiet] [-v, --verbose] [-y]
    [-c CONFIGFILE] [--dbpath DIRECTORY] [-r, --root DIRECTORY]

more options:
    [-h, --hash] [--force] [--oldpackage] [--justdb] [--test]
    [--ignoresize] [--ignorearch] [--exactarch]
    [--noconflicts] [--fileconflicts]
    [--nodeps] [--nodigest] [--nosignature]
    [--noorder] [--noscripts] [--notriggers]
    [--autoerase] [--installpkgs="pkg1 pkg2 pkg2 ..."]

Warning: Some of the install-options are not evaluated yet"""


#
# Main program
#
def main():
    # Our yum worker object
    yum = RpmYum(rpmconfig)

    # Disabled fileconflicts per default in yum
    rpmconfig.nofileconflicts = 1

    # Default is to be a little verbose.
    rpmconfig.verbose = 1

    # Argument parsing
    args = parseYumOptions(sys.argv[1:], yum)

    # Always use the same random sequence
    random.seed(12345)
    count = int(args[0])
    yum.setCommand("update")
    while count > 0:
        yum.processArgs([])
        resolver = yum.opresolver
        count -= 1
        if count % 2:
            pkglist = yum.repos[random.randrange(0, len(yum.repos))].getPkgList()
            pkg = pkglist[random.randrange(0, len(pkglist))]
            yum.setCommand("update")
            print "Updating package %s" % pkg.getNEVRA()
            resolver.update(pkg)
        else:
            pkglist = resolver.getList()
            pkg = pkglist[random.randrange(0, len(pkglist))]
            yum.setCommand("remove")
            print "Erasing package %s" % pkg.getNEVRA()
            resolver.erase(pkg)
        yum.runDepRes()
        yum.runCommand()

if __name__ == '__main__':
    dohotshot = 0
    if dohotshot:
        import tempfile, hotshot, hotshot.stats
        filename = tempfile.mktemp()
        prof = hotshot.Profile(filename)
        try:
            prof.runcall(main)
        except SystemExit:
            pass
        print "Starting profil statistics. This takes some time..."
        prof.close()
        del prof
        s = hotshot.stats.load(filename)
        s.strip_dirs().sort_stats('time').print_stats(100)
        s.strip_dirs().sort_stats('cumulative').print_stats(100)
        os.unlink(filename)
    else:
        main()

# vim:ts=4:sw=4:showmatch:expandtab
