#!/usr/bin/python
#
# This code may be distributed under the terms of the 
# GNU Public License, either version 2 of the license, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# Copyright 2004, 2005 Red Hat, Inc.
#
# Author: Phil Knirsch
#   

import sys, os.path

PYRPMDIR = os.path.dirname(__file__) + "/.."
if not PYRPMDIR in sys.path:
    sys.path.append(PYRPMDIR)

from pyrpm.package import *
from pyrpm.config import *
from pyrpm.cache import *
from pyrpm.database.rhndb import *

rhnrepo = RhnRepoDB(rpmconfig, None, rpmconfig.buildroot)
rhnrepo.read()

for pkg in rhnrepo.getPkgs():
    nc = pkg.yumrepo.getNetworkCache()
    pkg.source = os.path.join(nc.getBaseURL(), pkg.source)
    if not nc.isCached(pkg.source):
    	source = nc.cache(pkg.source)
    	print source
