#!/usr/bin/python
#
# Copyright (C) 2005 Red Hat, Inc.
# Copyright (C) 2005 Phil Knirsch
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Library General Public License as published by
# the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

# Best run this as non-root:
# - "mkdir /var/lib/pyrpm"
# - "chown test.test /var/lib/pyrpm"

import os, os.path, sys

PYRPMDIR = ".."
if not PYRPMDIR in sys.path:
    sys.path.append(PYRPMDIR)
from pyrpm import *

chrootdir = "/mnt/build/pyrpm-fc3-i386"
#chrootdir = ""
pyrpmhdrdir = "%s/var/lib/pyrpm/headers/" % chrootdir
rpmdir = "%s/var/lib/rpm" % chrootdir

if not os.path.isdir(pyrpmhdrdir):
    os.mkdir(pyrpmhdrdir)

rpmdb = RpmDB(rpmconfig, rpmdir)
rpmdb.read()

l = rpmdb.getPkgList()
for pkg in l:
    nevra = pkg.getNEVRA()
    pyrpmio = getRpmIOFactory(rpmconfig, "pydb:/%s%s" % (pyrpmhdrdir, nevra))
    try:
        pyrpmio.write(pkg)
    except IOError, e:
        sys.stderr.write("Couldn't write package header %s: %s! Aborting!\n"
                         % (nevra, e))
        sys.exit(1)

# vim:ts=4:sw=4:showmatch:expandtab
